// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Text$BsReactNative = require("bs-react-native/src/components/text.js");
var View$BsReactNative = require("bs-react-native/src/components/view.js");
var Style$BsReactNative = require("bs-react-native/src/style.js");
var StyleSheet$BsReactNative = require("bs-react-native/src/styleSheet.js");

var styles = StyleSheet$BsReactNative.create({
      container: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.flex(1),
            /* :: */[
              Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#374046"])),
              /* [] */0
            ]
          ]),
      navBar: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.flexDirection(/* Row */0),
            /* :: */[
              Style$BsReactNative.paddingTop(/* Pt */Block.__(0, [30])),
              /* :: */[
                Style$BsReactNative.height(/* Pt */Block.__(0, [64])),
                /* :: */[
                  Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#1EAAF1"])),
                  /* [] */0
                ]
              ]
            ]
          ]),
      navBarButton: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.color(/* String */Block.__(0, ["#FFFFFF"])),
            /* :: */[
              Style$BsReactNative.textAlign(/* Center */3),
              /* :: */[
                Style$BsReactNative.width(/* Pt */Block.__(0, [64])),
                /* [] */0
              ]
            ]
          ]),
      navBarHeader: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.flex(1),
            /* :: */[
              Style$BsReactNative.color(/* String */Block.__(0, ["#FFFFFF"])),
              /* :: */[
                Style$BsReactNative.fontWeight(/* Bold */737455525),
                /* :: */[
                  Style$BsReactNative.textAlign(/* Center */3),
                  /* [] */0
                ]
              ]
            ]
          ]),
      content: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.flex(1),
            /* :: */[
              Style$BsReactNative.justifyContent(/* Center */2),
              /* :: */[
                Style$BsReactNative.alignItems(/* Center */2),
                /* :: */[
                  Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#374046"])),
                  /* [] */0
                ]
              ]
            ]
          ]),
      text: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.color(/* String */Block.__(0, ["#EEEEEE"])),
            /* [] */0
          ])
    });

var component = ReasonReact.statelessComponent("Demo");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Caml_option.some(styles.container), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[
                              ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Caml_option.some(styles.navBar), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[
                                        ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Caml_option.some(styles.navBarButton), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Back"])),
                                        ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Caml_option.some(styles.navBarHeader), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Awesome App"])),
                                        ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Caml_option.some(styles.navBarButton), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["More"]))
                                      ])),
                              ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Caml_option.some(styles.content), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Caml_option.some(styles.text), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Welcome to Awesome App!"]))]))
                            ]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.styles = styles;
exports.component = component;
exports.make = make;
/* styles Not a pure module */
