// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var RNListItemGen = require("./RNListItem.gen");

function make(prim, prim$1, prim$2, prim$3) {
  return RNListItemGen.make(prim, prim$1, prim$2, prim$3);
}

exports.make = make;
/* ./RNListItem.gen Not a pure module */
