// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function commitDecode(json) {
  return {
          message: Json_decode.at(/* :: */[
                  "commit",
                  /* :: */[
                    "message",
                    /* [] */0
                  ]
                ], Json_decode.string)(json),
          author_name: Json_decode.at(/* :: */[
                  "commit",
                  /* :: */[
                    "author",
                    /* :: */[
                      "name",
                      /* [] */0
                    ]
                  ]
                ], Json_decode.string)(json),
          avatar_url: Json_decode.at(/* :: */[
                  "author",
                  /* :: */[
                    "avatar_url",
                    /* [] */0
                  ]
                ], Json_decode.string)(json)
        };
}

function commits(json) {
  return Json_decode.list(commitDecode, json);
}

var Decode = /* module */[
  /* commitDecode */commitDecode,
  /* commits */commits
];

var repoUrl = "https://api.github.com/repos/react-native-training/react-native-elements/commits";

function fetchCommits(param) {
  return fetch(repoUrl).then((function (prim) {
                    return prim.json();
                  })).then((function (json) {
                  var commits = Json_decode.list(commitDecode, json);
                  return Promise.resolve(commits);
                })).catch((function (_err) {
                return Promise.resolve(undefined);
              }));
}

exports.Decode = Decode;
exports.repoUrl = repoUrl;
exports.fetchCommits = fetchCommits;
/* No side effect */
