// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var RNGHListItemGen = require("./RNGHListItem.gen");

function make(prim, prim$1, prim$2) {
  return RNGHListItemGen.make(prim, prim$1, prim$2);
}

exports.make = make;
/* ./RNGHListItem.gen Not a pure module */
