// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var RNAvatarGen = require("./RNAvatar.gen");

function make(prim, prim$1, prim$2, prim$3, prim$4) {
  return RNAvatarGen.make(prim, prim$1, prim$2, prim$3, prim$4);
}

exports.make = make;
/* ./RNAvatar.gen Not a pure module */
