// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var ReactNativeElements = require("react-native-elements");

function make(placeholder, label, containerStyle, inputStyle, value, onChangeText, children) {
  return ReasonReact.wrapJsForReason(ReactNativeElements.Input, {
              placeholder: Js_null_undefined.fromOption(placeholder),
              onChangeText: Js_null_undefined.fromOption(onChangeText),
              label: Js_null_undefined.fromOption(label),
              containerStyle: Js_null_undefined.fromOption(containerStyle),
              inputStyle: Js_null_undefined.fromOption(inputStyle),
              value: Js_null_undefined.fromOption(value)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
