// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");
var RNInput2Gen = require("./RNInput2.gen");

function make(prim, prim$1, prim$2, prim$3, prim$4, prim$5, prim$6) {
  return RNInput2Gen.make(prim !== undefined ? Caml_option.valFromOption(prim) : undefined, prim$1 !== undefined ? Caml_option.valFromOption(prim$1) : undefined, prim$2 !== undefined ? Caml_option.valFromOption(prim$2) : undefined, prim$3 !== undefined ? Caml_option.valFromOption(prim$3) : undefined, prim$4 !== undefined ? Caml_option.valFromOption(prim$4) : undefined, prim$5 !== undefined ? Caml_option.valFromOption(prim$5) : undefined, prim$6);
}

exports.make = make;
/* ./RNInput2.gen Not a pure module */
