// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var ReactNativeElements = require("react-native-elements");

function make(title, children) {
  return ReasonReact.wrapJsForReason(ReactNativeElements.Header, {
              title: Js_null_undefined.fromOption(title)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
