// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var ReactNativeElements = require("react-native-elements");

function make(leftAvatar, title, subtitle, children) {
  return ReasonReact.wrapJsForReason(ReactNativeElements.ListItem, {
              leftAvatar: Js_null_undefined.fromOption(leftAvatar),
              title: Js_null_undefined.fromOption(title),
              subtitle: Js_null_undefined.fromOption(subtitle)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
