// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function getPlatform(param) {
  if (typeof window !== "undefined") {
    return /* Browser */0;
  } else {
    return /* Node */1;
  }
}

exports.getPlatform = getPlatform;
/* No side effect */
