// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");
var LodashDebounce = require("lodash.debounce");

function s(prim) {
  return prim;
}

function make($staropt$star, $staropt$star$1, f) {
  var wait = $staropt$star !== undefined ? $staropt$star : 0;
  var options = $staropt$star$1 !== undefined ? Caml_option.valFromOption($staropt$star$1) : { };
  return LodashDebounce(f, wait, options);
}

function call(input, f) {
  return f(input);
}

var Debounce = /* module */[
  /* make */make,
  /* call */call
];

exports.s = s;
exports.Debounce = Debounce;
/* lodash.debounce Not a pure module */
