// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Style$BsReactNative = require("bs-react-native/src/style.js");
var StyleSheet$BsReactNative = require("bs-react-native/src/styleSheet.js");

var containerStyle = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.marginBottom(/* Pt */Block.__(0, [10])),
      /* [] */0
    ]);

var inputStyle = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.height(/* Pt */Block.__(0, [46])),
      /* [] */0
    ]);

var InputS = /* module */[
  /* containerStyle */containerStyle,
  /* inputStyle */inputStyle
];

var containerStyle$1 = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.paddingHorizontal(/* Pt */Block.__(0, [10])),
      /* [] */0
    ]);

var ButtonS = /* module */[/* containerStyle */containerStyle$1];

var styles = StyleSheet$BsReactNative.create({
      container: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.display(/* Flex */0),
            /* :: */[
              Style$BsReactNative.flex(1),
              /* :: */[
                Style$BsReactNative.alignItems(/* Center */2),
                /* :: */[
                  Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#fff"])),
                  /* :: */[
                    Style$BsReactNative.height(/* Pct */Block.__(1, [100])),
                    /* :: */[
                      Style$BsReactNative.justifyContent(/* Center */2),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ])
    });

exports.InputS = InputS;
exports.ButtonS = ButtonS;
exports.styles = styles;
/* containerStyle Not a pure module */
