// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var Home$Gitphone = require("../shared/components/Home.bs.js");
var CommitList$Gitphone = require("../shared/components/CommitList.bs.js");
var FetchRepos$Gitphone = require("../shared/github/FetchRepos.bs.js");
var StackNavigator$BsReactNavigation = require("bs-react-navigation/src/StackNavigator.bs.js");

function getScreen(route, navigation) {
  switch (route) {
    case 0 : 
        return /* tuple */[
                ReasonReact.element(undefined, undefined, Home$Gitphone.make(navigation, /* array */[])),
                {
                  title: "Home"
                }
              ];
    case 1 : 
        return /* tuple */[
                ReasonReact.element(undefined, undefined, FetchRepos$Gitphone.make(navigation, /* array */[])),
                {
                  title: "FetchRepos"
                }
              ];
    case 2 : 
        return /* tuple */[
                ReasonReact.element(undefined, undefined, CommitList$Gitphone.make(navigation, /* array */[])),
                {
                  title: "CommitList"
                }
              ];
    
  }
}

var Stack = StackNavigator$BsReactNavigation.Create(/* module */[
      /* initialRoute : Home */0,
      /* getScreen */getScreen
    ]);

var render = Stack[/* render */11];

exports.Stack = Stack;
exports.render = render;
/* Stack Not a pure module */
