// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var ReactNativeElements = require("react-native-elements");

function make(buttonStyle, underlayColor, clear, containerStyle, disabled, disabledStyle, disabledTitleStyle, icon, iconContainerStyle, iconRight, loading, loadingProps, loadingStyle, onPress, title, titleProps, titleStyle, children) {
  return ReasonReact.wrapJsForReason(ReactNativeElements.Button, {
              buttonStyle: Js_null_undefined.fromOption(buttonStyle),
              underlayColor: Js_null_undefined.fromOption(underlayColor),
              clear: Js_null_undefined.fromOption(clear),
              containerStyle: Js_null_undefined.fromOption(containerStyle),
              disabled: Js_null_undefined.fromOption(disabled),
              disabledStyle: Js_null_undefined.fromOption(disabledStyle),
              disabledTitleStyle: Js_null_undefined.fromOption(disabledTitleStyle),
              icon: Js_null_undefined.fromOption(icon),
              iconContainerStyle: Js_null_undefined.fromOption(iconContainerStyle),
              iconRight: Js_null_undefined.fromOption(iconRight),
              loading: Js_null_undefined.fromOption(loading),
              loadingProps: Js_null_undefined.fromOption(loadingProps),
              loadingStyle: Js_null_undefined.fromOption(loadingStyle),
              onPress: Js_null_undefined.fromOption(onPress),
              title: Js_null_undefined.fromOption(title),
              titleProps: Js_null_undefined.fromOption(titleProps),
              titleStyle: Js_null_undefined.fromOption(titleStyle)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
