// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var RNIcons = require("bs-react-native-vector-icons/re/RNIcons.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Icons$Gitphone = require("./Icons.bs.js");
var Styles$Gitphone = require("../styles/Styles.bs.js");
var InputEl$Gitphone = require("../rnelements/InputEl.bs.js");
var ButtonEl$Gitphone = require("../rnelements/ButtonEl.bs.js");
var View$BsReactNative = require("bs-react-native/src/components/view.js");

var component = ReasonReact.statelessComponent("Home");

var renderPlaneIcon = ReasonReact.element(undefined, undefined, RNIcons.FontAwesome[/* make */1](/* _paperPlane */990601295, "white", 15, undefined, /* array */[]));

var renderPlaneIcon2 = ReasonReact.element(undefined, undefined, Icons$Gitphone.make("paper-plane", 15, "white")(/* array */[]));

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Caml_option.some(Styles$Gitphone.styles.container), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[
                              ReasonReact.element(undefined, undefined, InputEl$Gitphone.make("Github's owner", "Owner", Caml_option.some(Styles$Gitphone.InputS[/* containerStyle */0]), Caml_option.some(Styles$Gitphone.InputS[/* inputStyle */1]), /* array */[])),
                              ReasonReact.element(undefined, undefined, InputEl$Gitphone.make("Github's repository name", "Repo", Caml_option.some(Styles$Gitphone.InputS[/* containerStyle */0]), Caml_option.some(Styles$Gitphone.InputS[/* inputStyle */1]), /* array */[])),
                              ReasonReact.element(undefined, undefined, ButtonEl$Gitphone.make(Caml_option.some(Styles$Gitphone.ButtonS[/* containerStyle */0]), undefined, undefined, undefined, undefined, undefined, undefined, Caml_option.some(renderPlaneIcon2), undefined, undefined, undefined, undefined, undefined, undefined, "SUBMIT", undefined, undefined, /* array */[]))
                            ]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.renderPlaneIcon = renderPlaneIcon;
exports.renderPlaneIcon2 = renderPlaneIcon2;
exports.make = make;
/* component Not a pure module */
