// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var Icons$Gitphone = require("../rnelements/Icons.bs.js");
var Input$Gitphone = require("../rnelements/Input.bs.js");
var ButtonEl$Gitphone = require("../rnelements/ButtonEl.bs.js");
var View$BsReactNative = require("bs-react-native/src/components/view.js");

var component = ReasonReact.statelessComponent("Home");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[
                              ReasonReact.element(undefined, undefined, Input$Gitphone.make("Github's owner", "Owner", /* array */[])),
                              ReasonReact.element(undefined, undefined, Input$Gitphone.make("Github's repository name", "Repo", /* array */[])),
                              ReasonReact.element(undefined, undefined, ButtonEl$Gitphone.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "SUBMIT", undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, Icons$Gitphone.make("paper-plane", 15, "white")(/* array */[]))]))
                            ]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
