// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ButtonEl$Gitphone = require("./ButtonEl.bs.js");
var View$BsReactNative = require("bs-react-native/src/components/view.js");
var Style$BsReactNative = require("bs-react-native/src/style.js");
var StyleSheet$BsReactNative = require("bs-react-native/src/styleSheet.js");

var styles = StyleSheet$BsReactNative.create({
      container: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.flex(1),
            /* :: */[
              Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#fff"])),
              /* :: */[
                Style$BsReactNative.alignItems(/* Center */2),
                /* :: */[
                  Style$BsReactNative.justifyContent(/* Center */2),
                  /* [] */0
                ]
              ]
            ]
          ]),
      title: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.fontWeight(/* Bold */737455525),
            /* :: */[
              Style$BsReactNative.fontSize(/* Float */Block.__(0, [16])),
              /* [] */0
            ]
          ]),
      button: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.borderRadius(3),
            /* :: */[
              Style$BsReactNative.padding(/* Pt */Block.__(0, [20])),
              /* :: */[
                Style$BsReactNative.marginVertical(/* Pt */Block.__(0, [10])),
                /* :: */[
                  Style$BsReactNative.marginTop(/* Pt */Block.__(0, [10])),
                  /* :: */[
                    Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#1B95E0"])),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]),
      buttonText: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.color(/* String */Block.__(0, ["#fff"])),
            /* :: */[
              Style$BsReactNative.fontWeight(/* Bold */737455525),
              /* :: */[
                Style$BsReactNative.fontSize(/* Float */Block.__(0, [16])),
                /* [] */0
              ]
            ]
          ])
    });

var Styles = /* module */[/* styles */styles];

var component = ReasonReact.statelessComponent("MyButton");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, ButtonEl$Gitphone.make(Caml_option.some(styles.button), "#0A84D0", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function (_e) {
                                          console.log("CLICKED");
                                          return /* () */0;
                                        }), "Rotate Logo", undefined, Caml_option.some(styles.buttonText), /* array */[]))]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.Styles = Styles;
exports.component = component;
exports.make = make;
/* styles Not a pure module */
