// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Json = require("@glennsl/bs-json/src/Json.bs.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

var url = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22paris%2C%20france%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";

function parseWeatherJson(json) {
  return /* record */[
          /* summary */Json_decode.field("text", Json_decode.string, json),
          /* temp */Caml_format.caml_float_of_string(Json_decode.field("temp", Json_decode.string, json))
        ];
}

function parseWeatherResultsJson(json) {
  return Json_decode.at(/* :: */[
                "query",
                /* :: */[
                  "results",
                  /* :: */[
                    "channel",
                    /* :: */[
                      "item",
                      /* :: */[
                        "condition",
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ], parseWeatherJson)(Json.parseOrRaise(json));
}

function getWeather(param) {
  return fetch(url).then((function (prim) {
                  return prim.text();
                })).then((function (jsonText) {
                return Promise.resolve(parseWeatherResultsJson(jsonText));
              }));
}

exports.url = url;
exports.parseWeatherJson = parseWeatherJson;
exports.parseWeatherResultsJson = parseWeatherResultsJson;
exports.getWeather = getWeather;
/* No side effect */
