// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var StackNav$Gitphone = require("./router/StackNav.bs.js");

var stack = StackNav$Gitphone.render;

var app = StackNav$Gitphone.render;

exports.stack = stack;
exports.app = app;
/* StackNav-Gitphone Not a pure module */
