// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var Home$Gitphone = require("./components/Home.bs.js");

function app(param) {
  return ReasonReact.element(undefined, undefined, Home$Gitphone.make(/* array */[]));
}

exports.app = app;
/* ReasonReact Not a pure module */
