// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var ReactNativeElements = require("react-native-elements");

function make(placeholder, label, children) {
  return ReasonReact.wrapJsForReason(ReactNativeElements.Input, {
              placeholder: Js_null_undefined.fromOption(placeholder),
              label: Js_null_undefined.fromOption(label)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
